server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reaction_cut?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Tbw199878..
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  # 允许循环依赖
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.tbw.cut.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置
ffmpeg:
  path: /opt/homebrew/bin/ffmpeg
  video-storage-dir: /Users/tbw/Reaction
  temp-dir: /Users/tbw/Reaction/temp

download:
  threads: 3
  queue-size: 10

logging:
  level:
    com.tbw.cut: debug
    com.tbw.cut.utils.FFmpegUtil: info

# 队列配置
queue:
  processing:
    max-retry-count: 3
    retry-delay-minutes: 30
    batch-interval-ms: 5000
    min-task-interval-ms: 5000
    estimated-task-duration-minutes: 10